Use autoconf to check dependencies and set paths to utils

diff --git a/vcsh.in b/vcsh.in
--- a/vcsh.in
+++ b/vcsh.in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!@SHELL@
 
 # This program is licensed under the GNU GPL version 2 or later.
 # (c) Richard "RichiH" Hartmann <richih@debian.org>, 2011-2015
@@ -159,26 +159,26 @@ info() {
 clone() {
 	hook pre-clone
 	init
-	git remote add origin "$GIT_REMOTE"
-	git checkout -b "$VCSH_BRANCH" || return $?
-	git config branch."$VCSH_BRANCH".remote origin
-	git config branch."$VCSH_BRANCH".merge  refs/heads/"$VCSH_BRANCH"
-	if [ $(git ls-remote origin "$VCSH_BRANCH" 2> /dev/null | wc -l ) -lt 1 ]; then
+	@GIT@ remote add origin "$GIT_REMOTE"
+	@GIT@ checkout -b "$VCSH_BRANCH" || return $?
+	@GIT@ config branch."$VCSH_BRANCH".remote origin
+	@GIT@ config branch."$VCSH_BRANCH".merge  refs/heads/"$VCSH_BRANCH"
+	if [ $(@GIT@ ls-remote origin "$VCSH_BRANCH" 2> /dev/null | wc -l ) -lt 1 ]; then
 		info "remote is empty, not merging anything.
   You should add files to your new repository." # editorconfig-checker-disable-line
 		exit
 	fi
-	GIT_VERSION_MAJOR=$(git --version | sed -E -n 's/.* ([0-9]+)\..*/\1/p' )
+	GIT_VERSION_MAJOR=$(@GIT@ --version | @SED@ -E -n 's/.* ([0-9]+)\..*/\1/p' )
 	if [ 1 -lt "$GIT_VERSION_MAJOR" ];then
-		git fetch origin "$VCSH_BRANCH"
+		@GIT@ fetch origin "$VCSH_BRANCH"
 	else
-		git fetch origin
+		@GIT@ fetch origin
 	fi
 	hook pre-merge
-	git read-tree -n -mu origin/"$VCSH_BRANCH" \
+	@GIT@ read-tree -n -mu origin/"$VCSH_BRANCH" \
 		|| fatal "will stop after fetching and not try to merge!
   Once this situation has been resolved, run 'vcsh $VCSH_REPO_NAME pull' to finish cloning." 17 # editorconfig-checker-disable-line
-	git -c merge.ff=true merge origin/"$VCSH_BRANCH"
+	@GIT@ -c merge.ff=true merge origin/"$VCSH_BRANCH"
 	hook post-merge
 	hook post-clone
 	retire
@@ -192,7 +192,7 @@ commit() {
 		echo "$VCSH_REPO_NAME: "
 		GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
 		use
-		git commit --untracked-files=no --quiet "$@"
+		@GIT@ commit --untracked-files=no --quiet "$@"
 		VCSH_COMMAND_RETURN_CODE=$?
 		echo
 	done
@@ -203,7 +203,7 @@ delete() {
 	cd "$VCSH_BASE" || fatal "could not enter '$VCSH_BASE'" 11
 	use
 	info "This operation WILL DESTROY DATA!"
-	files=$(git ls-files)
+	files=$(@GIT@ ls-files)
 	echo "These files will be deleted:
 
 $files
@@ -230,7 +230,7 @@ foreach() {
 
 	# We default to prefixing `git` to all commands passed to foreach, but
 	# allow running in general context with -g
-	command_prefix=git
+	command_prefix=@GIT@
 	while getopts "g" flag; do
 		if [ x"$1" = x'-g' ]; then
 			unset command_prefix
@@ -263,7 +263,7 @@ init() {
 	[ ! -e "$GIT_DIR" ] || fatal "'$GIT_DIR' exists" 10
 	mkdir -p "$VCSH_BASE" || fatal "could not create '$VCSH_BASE'" 50
 	cd "$VCSH_BASE" || fatal "could not enter '$VCSH_BASE'" 11
-	git init --shared=false
+	@GIT@ init --shared=false
 	upgrade
 	hook post-init
 }
@@ -276,7 +276,7 @@ list() {
 
 get_files() {
 	GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
-	git ls-files --full-name
+	@GIT@ ls-files --full-name
 }
 
 list_tracked() {
@@ -291,7 +291,7 @@ list_tracked() {
 }
 
 list_tracked_helper() {
-	sed "s,^,$(printf '%s\n' "$VCSH_BASE/" | sed 's/[,\&]/\\&/g')," | sort -u
+	@SED@ "s,^,$(printf '%s\n' "$VCSH_BASE/" | @SED@ 's/[,\&]/\\&/g')," | sort -u
 }
 
 list_tracked_by() {
@@ -299,8 +299,6 @@ list_tracked_by() {
 }
 
 list_untracked() {
-	command -v 'comm' >/dev/null 2>&1 || fatal "Could not find 'comm'"
-
 	temp_file_others=$(mktemp "${TMPDIR:-/tmp}/tmp.XXXXXXXXXX") || fatal 'Could not create temp file'
 	temp_file_untracked=$(mktemp "${TMPDIR:-/tmp}/tmp.XXXXXXXXXX") || fatal 'Could not create temp file'
 	temp_file_untracked_copy=$(mktemp "${TMPDIR:-/tmp}/tmp.XXXXXXXXXX") || fatal 'Could not create temp file'
@@ -335,7 +333,7 @@ list_untracked() {
 
 list_untracked_helper() {
 	export GIT_DIR="$VCSH_REPO_D/$VCSH_REPO_NAME.git"
-	git ls-files --others $exclude_standard_opt "$directory_opt" | (
+	@GIT@ ls-files --others $exclude_standard_opt "$directory_opt" | (
 		while read line; do
 			echo "$line"
 			directory_component=${line%%/*}
@@ -347,7 +345,7 @@ list_untracked_helper() {
 		cp $temp_file_others $temp_file_untracked || fatal 'Could not copy temp file'
 	fi
 	cp $temp_file_untracked $temp_file_untracked_copy || fatal 'Could not copy temp file'
-	comm -12 $temp_file_others $temp_file_untracked_copy > $temp_file_untracked
+	@COMM@ -12 $temp_file_others $temp_file_untracked_copy > $temp_file_untracked
 }
 
 pull() {
@@ -356,7 +354,7 @@ pull() {
 		printf '%s: ' "$VCSH_REPO_NAME"
 		GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
 		use
-		git pull
+		@GIT@ pull
 		VCSH_COMMAND_RETURN_CODE=$?
 		echo
 	done
@@ -369,7 +367,7 @@ push() {
 		printf '%s: ' "$VCSH_REPO_NAME"
 		GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
 		use
-		git push
+		@GIT@ push
 		VCSH_COMMAND_RETURN_CODE=$?
 		echo
 	done
@@ -421,13 +419,13 @@ status_helper() {
 	GIT_DIR=$VCSH_REPO_D/$1.git; export GIT_DIR
 	VCSH_GIT_OPTIONS=$2
 	use
-	remote_tracking_branch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2> /dev/null) && {
-		commits_behind=$(git log ..${remote_tracking_branch} --oneline | wc -l)
-		commits_ahead=$(git log ${remote_tracking_branch}.. --oneline | wc -l)
+	remote_tracking_branch=$(@GIT@ rev-parse --abbrev-ref --symbolic-full-name @{u} 2> /dev/null) && {
+		commits_behind=$(@GIT@ log ..${remote_tracking_branch} --oneline | wc -l)
+		commits_ahead=$(@GIT@ log ${remote_tracking_branch}.. --oneline | wc -l)
 		[ ${commits_behind} -ne 0 ] && echo "Behind $remote_tracking_branch by $commits_behind commits"
 		[ ${commits_ahead} -ne 0 ] && echo "Ahead of $remote_tracking_branch by $commits_ahead commits"
 	}
-	git ${VCSH_GIT_OPTIONS} status --short --untracked-files='no'
+	@GIT@ ${VCSH_GIT_OPTIONS} status --short --untracked-files='no'
 	VCSH_COMMAND_RETURN_CODE=$?
 }
 
@@ -436,20 +434,20 @@ upgrade() {
 	# fake-bare repositories are not bare, actually. Set this to false
 	# because otherwise Git complains "fatal: core.bare and core.worktree
 	# do not make sense"
-	git config core.bare false
+	@GIT@ config core.bare false
 	# core.worktree may be absolute or relative to $GIT_DIR, depending on
 	# user preference
 	if [ ! "x$VCSH_WORKTREE" = 'xabsolute' ]; then
-		git config core.worktree "$(cd "$GIT_DIR" && GIT_WORK_TREE=$VCSH_BASE git rev-parse --show-cdup)"
+		@GIT@ config core.worktree "$(cd "$GIT_DIR" && GIT_WORK_TREE=$VCSH_BASE @GIT@ rev-parse --show-cdup)"
 	elif [ ! "x$VCSH_WORKTREE" = 'xrelative' ]; then
-		git config core.worktree "$VCSH_BASE"
+		@GIT@ config core.worktree "$VCSH_BASE"
 	fi
-	[ ! "x$VCSH_GITIGNORE" = 'xnone' ] && git config core.excludesfile ".gitignore.d/$VCSH_REPO_NAME"
-	[ ! "x$VCSH_GITATTRIBUTES" = 'xnone' ] && git config core.attributesfile ".gitattributes.d/$VCSH_REPO_NAME"
-	git config vcsh.vcsh 'true'
+	[ ! "x$VCSH_GITIGNORE" = 'xnone' ] && @GIT@ config core.excludesfile ".gitignore.d/$VCSH_REPO_NAME"
+	[ ! "x$VCSH_GITATTRIBUTES" = 'xnone' ] && @GIT@ config core.attributesfile ".gitattributes.d/$VCSH_REPO_NAME"
+	@GIT@ config vcsh.vcsh 'true'
 	use
-	[ -e "$VCSH_BASE/.gitignore.d/$VCSH_REPO_NAME" ] && git add -f "$VCSH_BASE/.gitignore.d/$VCSH_REPO_NAME"
-	[ -e "$VCSH_BASE/.gitattributes.d/$VCSH_REPO_NAME" ] && git add -f "$VCSH_BASE/.gitattributes.d/$VCSH_REPO_NAME"
+	[ -e "$VCSH_BASE/.gitignore.d/$VCSH_REPO_NAME" ] && @GIT@ add -f "$VCSH_BASE/.gitignore.d/$VCSH_REPO_NAME"
+	[ -e "$VCSH_BASE/.gitattributes.d/$VCSH_REPO_NAME" ] && @GIT@ add -f "$VCSH_BASE/.gitattributes.d/$VCSH_REPO_NAME"
 	hook post-upgrade
 }
 
@@ -460,7 +458,7 @@ use() {
 
 which() {
 	output=$(for VCSH_REPO_NAME in $(list); do
-		get_files | grep -- "$VCSH_COMMAND_PARAMETER" | sed "s/^/$VCSH_REPO_NAME: /"
+		get_files | @GREP@ -- "$VCSH_COMMAND_PARAMETER" | @SED@ "s/^/$VCSH_REPO_NAME: /"
 	done | sort -u)
 	if [ -z "$output" ]; then
 		fatal "'$VCSH_COMMAND_PARAMETER' does not exist" 1
@@ -478,12 +476,12 @@ write_gitignore() {
 
 	use
 	cd "$VCSH_BASE" || fatal "could not enter '$VCSH_BASE'" 11
-	local GIT_VERSION="$(git --version)"
-	local GIT_VERSION_MAJOR=$(echo $GIT_VERSION | sed -E -n 's/.* ([0-9]+)\..*/\1/p')
-	local GIT_VERSION_MINOR=$(echo $GIT_VERSION | sed -E -n 's/.* ([0-9]+)\.([0-9]+)\..*/\2/p')
+	local GIT_VERSION="$(@GIT@ --version)"
+	local GIT_VERSION_MAJOR=$(echo $GIT_VERSION | @SED@ -E -n 's/.* ([0-9]+)\..*/\1/p')
+	local GIT_VERSION_MINOR=$(echo $GIT_VERSION | @SED@ -E -n 's/.* ([0-9]+)\.([0-9]+)\..*/\2/p')
 	OLDIFS=$IFS
 	IFS=$(printf '\n\t')
-	gitignores=$(for file in $(git ls-files); do
+	gitignores=$(for file in $(@GIT@ ls-files); do
 		if [ $GIT_VERSION_MAJOR -ge 2 -a $GIT_VERSION_MINOR -ge 7 ]; then
 			echo "$file";
 		else
@@ -502,9 +500,9 @@ write_gitignore() {
 
 	echo '*' > "$tempfile" || fatal "could not write to '$tempfile'" 57
 	for gitignore in $gitignores; do
-		echo "$gitignore" | sed 's@^@!/@' >> "$tempfile" || fatal "could not write to '$tempfile'" 57
+		echo "$gitignore" | @SED@ 's@^@!/@' >> "$tempfile" || fatal "could not write to '$tempfile'" 57
 		if [ "x$VCSH_GITIGNORE" = 'xrecursive' ] && [ -d "$gitignore" ]; then
-			{ echo "$gitignore/*" | sed 's@^@!/@' >> "$tempfile" || fatal "could not write to '$tempfile'" 57; }
+			{ echo "$gitignore/*" | @SED@ 's@^@!/@' >> "$tempfile" || fatal "could not write to '$tempfile'" 57; }
 		fi
 	done
 	IFS=$OLDIFS
@@ -521,7 +519,7 @@ write_gitignore() {
 		fatal "could not move '$tempfile' to '$VCSH_BASE/.gitignore.d/$VCSH_REPO_NAME'" 53
 }
 
-debug $(git version)
+debug $(@GIT@ version)
 
 if [ ! "x$VCSH_GITIGNORE" = 'xexact' ] && [ ! "x$VCSH_GITIGNORE" = 'xnone' ] && [ ! "x$VCSH_GITIGNORE" = 'xrecursive' ]; then
 	fatal "'\$VCSH_GITIGNORE' must equal 'exact', 'none', or 'recursive'" 1
@@ -575,7 +573,7 @@ elif [ "$VCSH_COMMAND" = 'help' ]; then
 	help && exit
 elif [ "$VCSH_COMMAND" = 'version' ]; then
 	echo "$SELF $VERSION"
-	git version
+	@GIT@ version
 	exit
 elif [ x"$VCSH_COMMAND" = x'which' ]; then
 	[ -z "$2" ] && fatal "$VCSH_COMMAND: please specify a filename" 1
@@ -622,7 +620,7 @@ elif [ -n "$2" ]; then
 	GIT_DIR=$VCSH_REPO_D/$VCSH_REPO_NAME.git; export GIT_DIR
 	[ -d "$GIT_DIR" ] || { help; exit 1; }
 	shift 1
-	set -- "git" "$@"
+	set -- "@GIT@" "$@"
 elif [ -n "$VCSH_COMMAND" ]; then
 	VCSH_COMMAND='enter'; export VCSH_COMMAND
 	VCSH_REPO_NAME=$1; export VCSH_REPO_NAME
@@ -635,7 +633,7 @@ fi
 
 # Did we receive a directory instead of a name?
 # Mangle the input to fit normal operation.
-if echo "$VCSH_REPO_NAME" | grep -q '/'; then
+if echo "$VCSH_REPO_NAME" | @GREP@ -q '/'; then
 	GIT_DIR=$VCSH_REPO_NAME; export GIT_DIR
 	VCSH_REPO_NAME=$(basename "$VCSH_REPO_NAME" .git); export VCSH_REPO_NAME
 fi
@@ -657,7 +655,7 @@ check_dir "$VCSH_REPO_D"
 [ ! "x$VCSH_GITATTRIBUTES" = 'xnone' ] && check_dir "$VCSH_BASE/.gitattributes.d"
 
 verbose "$VCSH_COMMAND begin"
-VCSH_COMMAND=$(echo "$VCSH_COMMAND" | sed 's/-/_/g'); export VCSH_COMMAND
+VCSH_COMMAND=$(echo "$VCSH_COMMAND" | @SED@ 's/-/_/g'); export VCSH_COMMAND
 
 # Source repo-specific configuration file
 [ -r "$XDG_CONFIG_HOME/vcsh/config.d/$VCSH_REPO_NAME" ] && . "$XDG_CONFIG_HOME/vcsh/config.d/$VCSH_REPO_NAME"
