stash stuff away

diff --git a/vcsh b/vcsh
--- a/vcsh
+++ b/vcsh
@@ -281,6 +281,25 @@ do
 	fi
 done
 
+#shift
+## POSIX
+#while true; do
+#    case "$1" in
+#      -h|--help|-\?) show_help; exit 0;;
+#      -v|--verbose) verbose=1; shift;;
+#      -f) if [ $# -gt 1 ]; then
+#            output_file=$2; shift 2
+#          else
+#            echo "-f requires an argument" 1>&2
+#            exit 1
+#          fi ;;
+#      --) shift; break;;
+#      -*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
+#      *)  break;;
+#    esac
+#done
+#shift
+#
 verbose "$VCSH_COMMAND begin"
 export VCSH_COMMAND=$(echo $VCSH_COMMAND | sed 's/-/_/g')
 $VCSH_COMMAND
