Do not anchor the initial exclude-all
Obviously, the approach taken by vcsh wrt ~/.gitignore.d is
"exclude-all-except-listed". Hence, the initial '*' (exclude-all) must
not be anchored, else it wouldn't apply to subdirectories.

Signed-off-by: martin f. krafft <madduck@madduck.net>

diff --git a/vcsh b/vcsh
--- a/vcsh
+++ b/vcsh
@@ -256,7 +256,7 @@ write_gitignore() {
 		done;
 	done | sort -u)
 	tempfile=$(mktemp) || fatal "could not create tempfile" 51
-	echo '/*' > "$tempfile" || fatal "could not write to '$tempfile'" 57
+	echo '*' > "$tempfile" || fatal "could not write to '$tempfile'" 57
 	for gitignore in $gitignores; do
 		echo "$gitignore" | sed 's@^@!/@' >> "$tempfile" || fatal "could not write to '$tempfile'" 57
 		if [ x$VCSH_GITIGNORE = x'recursive' ] && [ -d "$gitignore" ]; then
