Upgrade error() + exit to fatal()
At first I was going to change `exit` to `return` in the spirit of 9357db5, but
I can't think of a good reason to just let this condition go as if it
was a success. Even if nothing needed doing in the end the fact that we
couldn't have done anything if we tried seems like it should be an error.

Co-authored-by: Dieter Plaetinck <dieter@plaetinck.be>

diff --git a/vcsh.in b/vcsh.in
--- a/vcsh.in
+++ b/vcsh.in
@@ -575,8 +575,7 @@ write_gitignore() {
 	done
 	IFS=$OLDIFS
 	if diff -N "$tempfile" "$VCSH_BASE/.gitignore.d/$VCSH_REPO_NAME" > /dev/null; then
-		rm -f "$tempfile" || error "could not delete '$tempfile'"
-		exit
+		rm -f "$tempfile" || fatal "could not delete '$tempfile'" 59
 	fi
 	if [ -e "$VCSH_BASE/.gitignore.d/$VCSH_REPO_NAME" ]; then
 		info "'$VCSH_BASE/.gitignore.d/$VCSH_REPO_NAME' differs from new data, moving it to '$VCSH_BASE/.gitignore.d/$VCSH_REPO_NAME.bak'"
