Test conditions for ~/.config

diff --git a/vcsh b/vcsh
--- a/vcsh
+++ b/vcsh
@@ -4,6 +4,18 @@
 
 SELF=$(basename $0)
 [ -z $XDG_CONFIG_HOME ] && XDG_CONFIG_HOME="$HOME/.config"
+for dir in $XDG_CONFIG_HOME $XDG_CONFIG_HOME/vcsh $XDG_CONFIG_HOME/vcsh/repo.d
+do
+
+    if [ ! -d $dir ]; then
+        if [ -e $dir ]; then
+            echo "$SELF: error: $dir exists but is not a directory" >&2
+            return 2
+        else
+            mkdir $dir || (echo "$SELF: error: could not create $dir" >&2; return 2)
+        fi  
+    fi
+done
 VCSH_BASE="$XDG_CONFIG_HOME/vcsh/repo.d"
 
 help() {
